# source the users bashrc if it exists
if [ -f "${HOME}/.bashrc" ] ; then
  source "${HOME}/.bashrc"
fi

# Stop automatic path conversion by MSYS2
export MSYS2_ARG_CONV_EXCL="*"

# 64 bit
export C_INCLUDE_PATH="/usr/local/include:/mingw64/include:/usr/include"
export PATH="$PATH:/mingw64/bin"

# Short cut to browser user agent
UA_FIREFOX="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"

# EOF

